/*
 * XenForo pikaday.min.js
 * Copyright 2010-2021 XenForo Ltd.
 * Released under the XenForo License Agreement: https://xenforo.com/license-agreement
 */
/*
 Pikaday

 Copyright ? 2014 David Bushell | BSD & MIT license | https://github.com/Pikaday/Pikaday
*/
(function(l,q){if("object"===typeof exports){try{var t=require("moment")}catch(e){}module.exports=q(t)}else"function"===typeof define&&define.amd?define(function(e){try{t=e("moment")}catch(w){}return q(t)}):l.Pikaday=q(l.moment)})(this,function(l){var q="function"===typeof l,t=!!window.addEventListener,e=window.document,w=window.setTimeout,h=function(a,b,d,c){t?a.addEventListener(b,d,!!c):a.attachEvent("on"+b,d)},r=function(a,b,d,c){t?a.removeEventListener(b,d,!!c):a.detachEvent("on"+b,d)},g=function(a,
b){return-1!==(" "+a.className+" ").indexOf(" "+b+" ")},B=function(a,b){g(a,b)||(a.className=""===a.className?b:a.className+" "+b)},x=function(a,b){b=(" "+a.className+" ").replace(" "+b+" "," ");b=b.trim?b.trim():b.replace(/^\s+|\s+$/g,"");a.className=b},C=function(a){return/Array/.test(Object.prototype.toString.call(a))},n=function(a){return/Date/.test(Object.prototype.toString.call(a))&&!isNaN(a.getTime())},M=function(a,b){return[31,0===a%4&&0!==a%100||0===a%400?29:28,31,30,31,30,31,31,30,31,30,
31][b]},E=function(a){n(a)&&a.setHours(0,0,0,0)},F=function(a,b){return a.getTime()===b.getTime()},u=function(a,b,d){var c,y;for(c in b)if((y=void 0!==a[c])&&"object"===typeof b[c]&&null!==b[c]&&void 0===b[c].nodeName)n(b[c])?d&&(a[c]=new Date(b[c].getTime())):C(b[c])?d&&(a[c]=b[c].slice(0)):a[c]=u({},b[c],d);else if(d||!y)a[c]=b[c];return a},D=function(a,b,d){if(e.createEvent){var c=e.createEvent("HTMLEvents");c.initEvent(b,!0,!1);c=u(c,d);a.dispatchEvent(c)}else e.createEventObject&&(c=e.createEventObject(),
c=u(c,d),a.fireEvent("on"+b,c))},G=function(a){0>a.month&&(a.year-=Math.ceil(Math.abs(a.month)/12),a.month+=12);11<a.month&&(a.year+=Math.floor(Math.abs(a.month)/12),a.month-=12);return a},m={field:null,bound:void 0,ariaLabel:"Use the arrow keys to pick a date",position:"bottom left",reposition:!0,format:"YYYY-MM-DD",toString:null,parse:null,defaultDate:null,setDefaultDate:!1,firstDay:0,formatStrict:!1,minDate:null,maxDate:null,yearRange:10,showWeekNumber:!1,pickWholeWeek:!1,minYear:0,maxYear:9999,
minMonth:void 0,maxMonth:void 0,startRange:null,endRange:null,isRTL:!1,yearSuffix:"",showMonthAfterYear:!1,showDaysInNextAndPreviousMonths:!1,enableSelectionDaysInNextAndPreviousMonths:!1,numberOfMonths:1,mainCalendar:"left",container:void 0,blurFieldOnSelect:!0,i18n:{previousMonth:"Previous Month",nextMonth:"Next Month",months:"January February March April May June July August September October November December".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" ")},theme:null,events:[],onSelect:null,onOpen:null,onClose:null,onDraw:null,keyboardInput:!0},N=function(a,b,d){for(b+=a.firstDay;7<=b;)b-=7;return d?a.i18n.weekdaysShort[b]:a.i18n.weekdays[b]},P=function(a){var b=[],d="false";if(a.isEmpty)if(a.showDaysInNextAndPreviousMonths)b.push("is-outside-current-month"),a.enableSelectionDaysInNextAndPreviousMonths||b.push("is-selection-disabled");else return'<td class="is-empty"></td>';a.isDisabled&&b.push("is-disabled");
a.isToday&&b.push("is-today");a.isSelected&&(b.push("is-selected"),d="true");a.hasEvent&&b.push("has-event");a.isInRange&&b.push("is-inrange");a.isStartRange&&b.push("is-startrange");a.isEndRange&&b.push("is-endrange");return'<td data-day="'+a.day+'" class="'+b.join(" ")+'" aria-selected="'+d+'"><button class="pika-button pika-day" type="button" data-pika-year="'+a.year+'" data-pika-month="'+a.month+'" data-pika-day="'+a.day+'">'+a.day+"</button></td>"},Q=function(a,b,d){a=new Date(d,b,a);q?a=l(a).isoWeek():
(a.setHours(0,0,0,0),b=a.getDate(),d=a.getDay(),a.setDate(b+3-(d+7-1)%7),b=new Date(a.getFullYear(),0,4),a=(a.getTime()-b.getTime())/864E5,a=1+Math.round((a-3+(b.getDay()+7-1)%7)/7));return'<td class="pika-week">'+a+"</td>"},R=function(a,b,d,c){return'<tr class="pika-row'+(d?" pick-whole-week":"")+(c?" is-selected":"")+'">'+(b?a.reverse():a).join("")+"</tr>"},J=function(a,b,d,c,y,e){var f,k=a._o,g=d===k.minYear,n=d===k.maxYear;e='<div id="'+e+'" class="pika-title" role="heading" aria-live="assertive">';
var O=!0,h=!0;var m=[];for(f=0;12>f;f++)m.push('<option value="'+(d===y?f-b:12+f-b)+'"'+(f===c?' selected="selected"':"")+(g&&f<k.minMonth||n&&f>k.maxMonth?' disabled="disabled"':"")+">"+k.i18n.months[f]+"</option>");y='<div class="pika-label">'+k.i18n.months[c]+'<select class="pika-select pika-select-month" tabindex="-1">'+m.join("")+"</select></div>";if(C(k.yearRange)){f=k.yearRange[0];var l=k.yearRange[1]+1}else f=d-k.yearRange,l=1+d+k.yearRange;for(m=[];f<l&&f<=k.maxYear;f++)f>=k.minYear&&m.push('<option value="'+
f+'"'+(f===d?' selected="selected"':"")+">"+f+"</option>");d='<div class="pika-label">'+d+k.yearSuffix+'<select class="pika-select pika-select-year" tabindex="-1">'+m.join("")+"</select></div>";e=k.showMonthAfterYear?e+(d+y):e+(y+d);g&&(0===c||k.minMonth>=c)&&(O=!1);n&&(11===c||k.maxMonth<=c)&&(h=!1);0===b&&(e+='<button class="pika-prev'+(O?"":" is-disabled")+'" type="button">'+k.i18n.previousMonth+"</button>");b===a._o.numberOfMonths-1&&(e+='<button class="pika-next'+(h?"":" is-disabled")+'" type="button">'+
k.i18n.nextMonth+"</button>");return e+"</div>"},H=function(a){var b=this,d=b.config(a);b._onMouseDown=function(a){if(b._v){a=a||window.event;var c=a.target||a.srcElement;if(c)if(g(c,"is-disabled")||(!g(c,"pika-button")||g(c,"is-empty")||g(c.parentNode,"is-disabled")?g(c,"pika-prev")?b.prevMonth():g(c,"pika-next")&&b.nextMonth():(b.setDate(new Date(c.getAttribute("data-pika-year"),c.getAttribute("data-pika-month"),c.getAttribute("data-pika-day"))),d.bound&&w(function(){b.hide();d.blurFieldOnSelect&&
d.field&&d.field.blur()},100))),g(c,"pika-select"))b._c=!0;else if(a.preventDefault)a.preventDefault();else return a.returnValue=!1}};b._onChange=function(a){a=a||window.event;(a=a.target||a.srcElement)&&(g(a,"pika-select-month")?b.gotoMonth(a.value):g(a,"pika-select-year")&&b.gotoYear(a.value))};b._onKeyChange=function(a){a=a||window.event;if(b.isVisible())switch(a.keyCode){case 13:case 27:d.field&&d.field.blur();break;case 37:b.adjustDate("subtract",1);break;case 38:b.adjustDate("subtract",7);break;
case 39:b.adjustDate("add",1);break;case 40:b.adjustDate("add",7)}};b._parseFieldValue=function(){if(d.parse)return d.parse(d.field.value,d.format);if(q){var a=l(d.field.value,d.format,d.formatStrict);return a&&a.isValid()?a.toDate():null}return new Date(Date.parse(d.field.value))};b._onInputChange=function(a){a.firedBy!==b&&(a=b._parseFieldValue(),n(a)&&b.setDate(a),b._v||b.show())};b._onInputFocus=function(){b.show()};b._onInputClick=function(){b.show()};b._onInputBlur=function(){var a=e.activeElement;
do if(g(a,"pika-single"))return;while(a=a.parentNode);b._c||(b._b=w(function(){b.hide()},50));b._c=!1};b._onClick=function(a){a=a||window.event;var c=a=a.target||a.srcElement;if(a){t||!g(a,"pika-select")||a.onchange||(a.setAttribute("onchange","return;"),h(a,"change",b._onChange));do if(g(c,"pika-single")||c===d.trigger)return;while(c=c.parentNode);b._v&&a!==d.trigger&&c!==d.trigger&&b.hide()}};b.el=e.createElement("div");b.el.className="pika-single"+(d.isRTL?" is-rtl":"")+(d.theme?" "+d.theme:"");
h(b.el,"mousedown",b._onMouseDown,!0);h(b.el,"touchend",b._onMouseDown,!0);h(b.el,"change",b._onChange);d.keyboardInput&&h(e,"keydown",b._onKeyChange);d.field&&(d.container?d.container.appendChild(b.el):d.bound?e.body.appendChild(b.el):d.field.parentNode.insertBefore(b.el,d.field.nextSibling),h(d.field,"change",b._onInputChange),d.defaultDate||(d.defaultDate=b._parseFieldValue(),d.setDefaultDate=!0));a=d.defaultDate;n(a)?d.setDefaultDate?b.setDate(a,!0):b.gotoDate(a):b.gotoDate(new Date);d.bound?
(this.hide(),b.el.className+=" is-bound",h(d.trigger,"click",b._onInputClick),h(d.trigger,"focus",b._onInputFocus),h(d.trigger,"blur",b._onInputBlur)):this.show()};H.prototype={config:function(a){this._o||(this._o=u({},m,!0));a=u(this._o,a,!0);a.isRTL=!!a.isRTL;a.field=a.field&&a.field.nodeName?a.field:null;a.theme="string"===typeof a.theme&&a.theme?a.theme:null;a.bound=!!(void 0!==a.bound?a.field&&a.bound:a.field);a.trigger=a.trigger&&a.trigger.nodeName?a.trigger:a.field;a.disableWeekends=!!a.disableWeekends;
a.disableDayFn="function"===typeof a.disableDayFn?a.disableDayFn:null;var b=parseInt(a.numberOfMonths,10)||1;a.numberOfMonths=4<b?4:b;n(a.minDate)||(a.minDate=!1);n(a.maxDate)||(a.maxDate=!1);a.minDate&&a.maxDate&&a.maxDate<a.minDate&&(a.maxDate=a.minDate=!1);a.minDate&&this.setMinDate(a.minDate);a.maxDate&&this.setMaxDate(a.maxDate);C(a.yearRange)?(b=(new Date).getFullYear()-10,a.yearRange[0]=parseInt(a.yearRange[0],10)||b,a.yearRange[1]=parseInt(a.yearRange[1],10)||b):(a.yearRange=Math.abs(parseInt(a.yearRange,
10))||m.yearRange,100<a.yearRange&&(a.yearRange=100));return a},toString:function(a){a=a||this._o.format;return n(this._d)?this._o.toString?this._o.toString(this._d,a):q?l(this._d).format(a):this._d.toDateString():""},getMoment:function(){return q?l(this._d):null},setMoment:function(a,b){q&&l.isMoment(a)&&this.setDate(a.toDate(),b)},getDate:function(){return n(this._d)?new Date(this._d.getTime()):null},setDate:function(a,b){if(!a)return this._d=null,this._o.field&&(this._o.field.value="",D(this._o.field,
"change",{firedBy:this})),this.draw();"string"===typeof a&&(a=new Date(Date.parse(a)));if(n(a)){var d=this._o.minDate,c=this._o.maxDate;n(d)&&a<d?a=d:n(c)&&a>c&&(a=c);this._d=new Date(a.getTime());E(this._d);this.gotoDate(this._d);this._o.field&&(this._o.field.value=this.toString(),D(this._o.field,"change",{firedBy:this}));b||"function"!==typeof this._o.onSelect||this._o.onSelect.call(this,this.getDate())}},clear:function(){this.setDate(null)},gotoDate:function(a){var b=!0;if(n(a)){if(this.calendars){b=
new Date(this.calendars[0].year,this.calendars[0].month,1);var d=new Date(this.calendars[this.calendars.length-1].year,this.calendars[this.calendars.length-1].month,1),c=a.getTime();d.setMonth(d.getMonth()+1);d.setDate(d.getDate()-1);b=c<b.getTime()||d.getTime()<c}b&&(this.calendars=[{month:a.getMonth(),year:a.getFullYear()}],"right"===this._o.mainCalendar&&(this.calendars[0].month+=1-this._o.numberOfMonths));this.adjustCalendars()}},adjustDate:function(a,b){var d=this.getDate()||new Date;b=864E5*
parseInt(b);var c;"add"===a?c=new Date(d.valueOf()+b):"subtract"===a&&(c=new Date(d.valueOf()-b));this.setDate(c)},adjustCalendars:function(){this.calendars[0]=G(this.calendars[0]);for(var a=1;a<this._o.numberOfMonths;a++)this.calendars[a]=G({month:this.calendars[0].month+a,year:this.calendars[0].year});this.draw()},gotoToday:function(){this.gotoDate(new Date)},gotoMonth:function(a){isNaN(a)||(this.calendars[0].month=parseInt(a,10),this.adjustCalendars())},nextMonth:function(){this.calendars[0].month++;
this.adjustCalendars()},prevMonth:function(){this.calendars[0].month--;this.adjustCalendars()},gotoYear:function(a){isNaN(a)||(this.calendars[0].year=parseInt(a,10),this.adjustCalendars())},setMinDate:function(a){a instanceof Date?(E(a),this._o.minDate=a,this._o.minYear=a.getFullYear(),this._o.minMonth=a.getMonth()):(this._o.minDate=m.minDate,this._o.minYear=m.minYear,this._o.minMonth=m.minMonth,this._o.startRange=m.startRange);this.draw()},setMaxDate:function(a){a instanceof Date?(E(a),this._o.maxDate=
a,this._o.maxYear=a.getFullYear(),this._o.maxMonth=a.getMonth()):(this._o.maxDate=m.maxDate,this._o.maxYear=m.maxYear,this._o.maxMonth=m.maxMonth,this._o.endRange=m.endRange);this.draw()},setStartRange:function(a){this._o.startRange=a},setEndRange:function(a){this._o.endRange=a},draw:function(a){if(this._v||a){var b=this._o,d=b.minYear,c=b.maxYear,e=b.minMonth,g=b.maxMonth;a="";this._y<=d&&(this._y=d,!isNaN(e)&&this._m<e&&(this._m=e));this._y>=c&&(this._y=c,!isNaN(g)&&this._m>g&&(this._m=g));for(c=
0;c<b.numberOfMonths;c++)d="pika-title-"+Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,2),a+='<div class="pika-lendar">'+J(this,c,this.calendars[c].year,this.calendars[c].month,this.calendars[0].year,d)+this.render(this.calendars[c].year,this.calendars[c].month,d)+"</div>";this.el.innerHTML=a;b.bound&&"hidden"!==b.field.type&&w(function(){b.trigger.focus()},1);if("function"===typeof this._o.onDraw)this._o.onDraw(this);b.bound&&b.field.setAttribute("aria-label",b.ariaLabel)}},adjustPosition:function(){var a,
b;if(!this._o.container){this.el.style.position="absolute";var d=a=this._o.trigger;var c=this.el.offsetWidth;var g=this.el.offsetHeight;var n=window.innerWidth||e.documentElement.clientWidth;var f=window.innerHeight||e.documentElement.clientHeight;var k=window.pageYOffset||e.body.scrollTop||e.documentElement.scrollTop;var m=b=!0;if("function"===typeof a.getBoundingClientRect){d=a.getBoundingClientRect();var h=d.left+window.pageXOffset;var l=d.bottom+window.pageYOffset}else for(h=d.offsetLeft,l=d.offsetTop+
d.offsetHeight;d=d.offsetParent;)h+=d.offsetLeft,l+=d.offsetTop;if(this._o.reposition&&h+c>n||-1<this._o.position.indexOf("right")&&0<h-c+a.offsetWidth)h=h-c+a.offsetWidth,b=!1;if(this._o.reposition&&l+g>f+k||-1<this._o.position.indexOf("top")&&0<l-g-a.offsetHeight)l=l-g-a.offsetHeight,m=!1;this.el.style.left=h+"px";this.el.style.top=l+"px";B(this.el,b?"left-aligned":"right-aligned");B(this.el,m?"bottom-aligned":"top-aligned");x(this.el,b?"right-aligned":"left-aligned");x(this.el,m?"top-aligned":
"bottom-aligned")}},render:function(a,b,d){var c=this._o,e=new Date,g=M(a,b),f=(new Date(a,b,1)).getDay(),k=[],h=[];E(e);0<c.firstDay&&(f-=c.firstDay,0>f&&(f+=7));for(var l=0===b?11:b-1,m=11===b?0:b+1,q=0===b?a-1:a,r=11===b?a+1:a,t=M(q,l),u=g+f,z=u;7<z;)z-=7;u+=7-z;z=!1;for(var v=0,w=0;v<u;v++){var p=new Date(a,b,1+(v-f)),B=n(this._d)?F(p,this._d):!1,x=F(p,e),C=-1!==c.events.indexOf(p.toDateString())?!0:!1,D=v<f||v>=g+f,I=1+(v-f),K=b,L=a,G=c.startRange&&F(c.startRange,p),H=c.endRange&&F(c.endRange,
p),J=c.startRange&&c.endRange&&c.startRange<p&&p<c.endRange,A;!(A=c.minDate&&p<c.minDate||c.maxDate&&p>c.maxDate)&&(A=c.disableWeekends)&&(A=p.getDay(),A=0===A||6===A);p=A||c.disableDayFn&&c.disableDayFn(p);D&&(v<f?(I=t+I,K=l,L=q):(I-=g,K=m,L=r));x={day:I,month:K,year:L,hasEvent:C,isSelected:B,isToday:x,isDisabled:p,isEmpty:D,isStartRange:G,isEndRange:H,isInRange:J,showDaysInNextAndPreviousMonths:c.showDaysInNextAndPreviousMonths,enableSelectionDaysInNextAndPreviousMonths:c.enableSelectionDaysInNextAndPreviousMonths};
c.pickWholeWeek&&B&&(z=!0);h.push(P(x));7===++w&&(c.showWeekNumber&&h.unshift(Q(v-f,b,a)),k.push(R(h,c.isRTL,c.pickWholeWeek,z)),h=[],w=0,z=!1)}b=[];c.showWeekNumber&&b.push("<th></th>");for(a=0;7>a;a++)b.push('<th scope="col"><abbr title="'+N(c,a)+'">'+N(c,a,!0)+"</abbr></th>");c="<thead><tr>"+(c.isRTL?b.reverse():b).join("")+"</tr></thead>";return'<table cellpadding="0" cellspacing="0" class="pika-table" role="grid" aria-labelledby="'+d+'">'+c+("<tbody>"+k.join("")+"</tbody>")+"</table>"},isVisible:function(){return this._v},
show:function(){this.isVisible()||(this._v=!0,this.draw(),x(this.el,"is-hidden"),this._o.bound&&(h(e,"click",this._onClick),this.adjustPosition()),"function"===typeof this._o.onOpen&&this._o.onOpen.call(this))},hide:function(){var a=this._v;!1!==a&&(this._o.bound&&r(e,"click",this._onClick),this.el.style.position="static",this.el.style.left="auto",this.el.style.top="auto",B(this.el,"is-hidden"),this._v=!1,void 0!==a&&"function"===typeof this._o.onClose&&this._o.onClose.call(this))},destroy:function(){var a=
this._o;this.hide();r(this.el,"mousedown",this._onMouseDown,!0);r(this.el,"touchend",this._onMouseDown,!0);r(this.el,"change",this._onChange);a.keyboardInput&&r(e,"keydown",this._onKeyChange);a.field&&(r(a.field,"change",this._onInputChange),a.bound&&(r(a.trigger,"click",this._onInputClick),r(a.trigger,"focus",this._onInputFocus),r(a.trigger,"blur",this._onInputBlur)));this.el.parentNode&&this.el.parentNode.removeChild(this.el)}};return H});

var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
!function(a,b,c,d){XF.DateInput=XF.Element.newHandler({options:{weekStart:0,minDate:null,maxDate:null,disableWeekends:!1,yearRange:null,showWeekNumber:!1,showDaysInNextAndPreviousMonths:!0},picker:null,init:function(){var a=this.options.minDate,c=this.options.maxDate;if(a){var b=Date.parse(a.replace(/-/g,"/"));a=new Date(b)}c&&(b=Date.parse(c.replace(/-/g,"/")),c=new Date(b));var d=this,g=this.$target;b=g.val();a={format:"YYYY-MM-DD",toString:function(a,c){c=a.getDate();var b=a.getMonth()+1;return a.getFullYear()+
"-"+b+"-"+c},parse:function(a,c){var b=a.split("-");a=parseInt(b[0],10);c=parseInt(b[1],10)-1;b=parseInt(b[2],10);return new Date(a,c,b)},onSelect:function(){var a=this._d,b=String(a.getDate()),c=String(a.getMonth()+1);a=String(a.getFullYear());d.$target.val(a+"-"+(10>c?"0"+c:c)+"-"+(10>b?"0"+b:b))},onOpen:function(){g.prop("readonly")&&this.hide()},showTime:!1,firstDay:this.options.weekStart,minDate:a,maxDate:c,disableWeekends:this.options.disableWeekends,yearRange:this.options.yearRange,showWeekNumber:this.options.showWeekNumber,
showDaysInNextAndPreviousMonths:this.options.showDaysInNextAndPreviousMonths,i18n:{previousMonth:"",nextMonth:"",weekdays:[0,1,2,3,4,5,6].map(function(a){return XF.phrase("day"+a)}),weekdaysShort:[0,1,2,3,4,5,6].map(function(a){return XF.phrase("dayShort"+a)}),months:[0,1,2,3,4,5,6,7,8,9,10,11].map(function(a){return XF.phrase("month"+a)})},isRTL:!1,field:this.$target[0]};b&&(c=b.match(/^(\d{4})-(\d\d?)-(\d\d?)$/))&&(a.defaultDate=new Date(parseInt(c[1],10),parseInt(c[2],10)-1,parseInt(c[3])),a.setDefaultDate=
!0);this.picker=new Pikaday(a);this.$target.val(b);b=this.$target.parent().find(".js-dateTrigger");if(b.length)b.on("click",function(){d.picker.show()})}});XF.Element.register("date-input","XF.DateInput")}(jQuery,window,document);